# Generated by Django 3.0 on 2020-01-07 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_factsignup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admno',
            new_name='admnno',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='gaurdian',
            new_name='guardian',
        ),
    ]
