# Generated by Django 3.0 on 2020-01-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20200107_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentattendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdid', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('hours1status', models.CharField(max_length=10)),
                ('hours2status', models.CharField(max_length=10)),
                ('hours3status', models.CharField(max_length=10)),
                ('hours4status', models.CharField(max_length=10)),
            ],
        ),
    ]
