# Generated by Django 3.0 on 2020-01-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_applyleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='facultytattendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField(max_length=10)),
                ('hours1status', models.CharField(max_length=10)),
                ('hours2status', models.CharField(max_length=10)),
                ('hours3status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='leavefact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('to', models.CharField(max_length=20)),
                ('leavereason', models.CharField(max_length=20)),
                ('fromdate', models.DateField(max_length=10)),
                ('todate', models.DateField(max_length=10)),
            ],
        ),
    ]
