# Generated by Django 3.0 on 2020-01-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_facultytattendence_leavefact'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=20)),
                ('assessmentno', models.IntegerField(default=0, unique=True)),
                ('sub1mark', models.IntegerField(default=0, unique=True)),
                ('sub2mark', models.IntegerField(default=0, unique=True)),
                ('sub3mark', models.IntegerField(default=0, unique=True)),
                ('percentage', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='facultytattendence',
            new_name='factattend',
        ),
    ]
